# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
    push:
        branches: [cd-setup]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js version 16.13.1
              uses: actions/setup-node@v2
              with:
                  node-version: 16.13.1
                  cache: 'npm'
            - run: npm run build --if-present
